version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: apps/api/
      dockerfile: Dockerfile
    container_name: nest_api
    depends_on:
      - postgres
    environment:
      API_PORT: ${API_PORT}
      INFURA_API_KEY: ${INFURA_API_KEY}
      FUSDC_ADDRESS: ${FUSDC_ADDRESS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"

  website:
    build:
      context: apps/website/
      dockerfile: Dockerfile
    container_name: next_website
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "80:3000"

volumes:
  postgres_data:

# env_file:
#   - .env  # This ensures .env variables are loaded
