/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FUSDC_ABI } from "./FUSDC_ABI";
export * as factories from "./factories";
export { FUSDC_ABI__factory } from "./factories/FUSDC_ABI__factory";
